# Generated by Django 4.2.4 on 2023-09-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizprogress',
            name='answered_questions',
            field=models.ManyToManyField(to='quizz.question'),
        ),
    ]
