# Generated by Django 4.2.4 on 2023-09-02 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0002_category_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='time_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quizz.timecategory'),
        ),
    ]
