# Generated by Django 4.2.4 on 2023-09-08 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0002_quizprogress_answered_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizprogress',
            name='time_category',
        ),
    ]
