# Generated by Django 4.2.4 on 2023-09-02 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0003_timecategory_category_time_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='time_category',
        ),
    ]
