# Generated by Django 4.2.4 on 2023-09-03 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizz', '0004_remove_category_time_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer_text1',
            new_name='answer_text',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='answer_text2',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='answer_text3',
        ),
        migrations.CreateModel(
            name='QuizProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizz.category')),
                ('time_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizz.timecategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
