# Generated by Django 4.2.4 on 2023-09-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0005_rename_answer_text1_answer_answer_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizprogress',
            name='finish_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
