# Generated by Django 4.2.4 on 2023-09-10 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("quizz", "0007_alter_question_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quizprogress",
            name="category",
        ),
        migrations.RemoveField(
            model_name="quizprogress",
            name="answered_questions",
        ),
        migrations.AddField(
            model_name="quizprogress",
            name="answered_questions",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="quizz.question",
            ),
        ),
    ]
