# Generated by Django 4.2.4 on 2023-09-10 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("quizz", "0008_remove_quizprogress_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizprogress",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="quizz.category",
            ),
        ),
        migrations.RemoveField(
            model_name="quizprogress",
            name="answered_questions",
        ),
        migrations.AddField(
            model_name="quizprogress",
            name="answered_questions",
            field=models.ManyToManyField(to="quizz.question"),
        ),
    ]
