# Generated by Django 4.2.4 on 2023-09-12 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("quizz", "0011_alter_comment_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizprogress",
            name="time_base",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progress",
                to="quizz.timecategory",
            ),
        ),
    ]
