# Generated by Django 4.2.4 on 2023-09-13 22:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("quizz", "0012_quizprogress_time_base"),
    ]

    operations = [
        migrations.CreateModel(
            name="Books",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cover", models.ImageField(null=True, upload_to="static/files")),
                ("title", models.CharField(max_length=100)),
                ("desc", models.TextField()),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("category", models.ManyToManyField(to="quizz.category")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
