# Generated by Django 4.2.4 on 2023-09-13 23:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quizz", "0013_books"),
    ]

    operations = [
        migrations.RenameField(
            model_name="books",
            old_name="desc",
            new_name="description",
        ),
    ]
