# Generated by Django 4.2.4 on 2023-09-13 23:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizz", "0014_rename_desc_books_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="books",
            name="author",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
