# Generated by Django 4.2.4 on 2023-09-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizz", "0018_alter_books_cover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="books",
            name="cover",
            field=models.ImageField(null=True, upload_to="static/covers"),
        ),
    ]
