# Generated by Django 4.2.4 on 2023-09-15 20:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizz", "0019_alter_books_cover"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizprogress",
            name="answered_questions_order",
            field=models.JSONField(default=list),
        ),
    ]
