# Generated by Django 4.2.4 on 2023-09-15 21:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizz", "0020_quizprogress_answered_questions_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quizprogress",
            name="answered_questions_order",
        ),
        migrations.AddField(
            model_name="quizprogress",
            name="answered_order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
