# Generated by Django 4.2.4 on 2023-09-17 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("quizz", "0021_remove_quizprogress_answered_questions_order_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quizprogress",
            name="answered_order",
        ),
        migrations.RemoveField(
            model_name="quizprogress",
            name="answered_questions",
        ),
        migrations.CreateModel(
            name="SelectedQnA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quizz.answer"
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quizz.question"
                    ),
                ),
                (
                    "quiz_progress",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selected_answers",
                        to="quizz.quizprogress",
                    ),
                ),
            ],
        ),
    ]
