# Generated by Django 4.2.4 on 2023-09-17 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("quizz", "0022_remove_quizprogress_answered_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizprogress",
            name="answer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="quizz.answer",
            ),
        ),
        migrations.AddField(
            model_name="quizprogress",
            name="question",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="quizz.question",
            ),
        ),
        migrations.DeleteModel(
            name="SelectedQnA",
        ),
    ]
