# Generated by Django 4.2.4 on 2023-09-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizz", "0023_quizprogress_answer_quizprogress_question_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quizprogress",
            name="question",
        ),
        migrations.AddField(
            model_name="quizprogress",
            name="questions",
            field=models.ManyToManyField(to="quizz.question"),
        ),
        migrations.RemoveField(
            model_name="quizprogress",
            name="answer",
        ),
        migrations.AddField(
            model_name="quizprogress",
            name="answer",
            field=models.ManyToManyField(to="quizz.answer"),
        ),
    ]
