# Generated by Django 4.2.4 on 2023-09-17 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("quizz", "0024_remove_quizprogress_question_quizprogress_questions_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Answered",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quizz.question"
                    ),
                ),
                (
                    "quiz_progress",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quizz.quizprogress",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="UserAnswer",
        ),
    ]
