# Generated by Django 4.2.4 on 2023-11-03 22:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizz", "0026_useranswer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(blank=True, upload_to="static/files"),
        ),
    ]
