# Generated by Django 4.2.4 on 2023-09-12 22:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_alter_userprofile_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Interest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="userprofile",
            name="email",
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="interests",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="interests",
            field=models.ManyToManyField(to="authentication.interest"),
        ),
    ]
