# Generated by Django 4.2.4 on 2023-09-12 22:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizz", "0012_quizprogress_time_base"),
        ("authentication", "0003_interest_userprofile_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="interests",
            field=models.ManyToManyField(to="quizz.category"),
        ),
    ]
