# Generated by Django 4.2.4 on 2023-09-12 23:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0004_alter_userprofile_interests"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Interest",
        ),
    ]
